### ISSUE TITLE
Error while building on AWS

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/ARGO-container#5]
`/bin/sh -c conda install -c anaconda csvkit' returned a non-zero code: 1`

![image](https://user-images.githubusercontent.com/4397663/36083858-c900b7a2-0f74-11e8-959b-2a336b5ec0e2.png)

**Comment by aaron-15** [comment]
I didn't get this error. Which ami are you using?

**Comment by vr00n** [comment]
ami-1ee65166

**Comment by vr00n** [comment]
via @gperrin12  

![image](https://user-images.githubusercontent.com/4397663/38773080-0601f766-4002-11e8-8c14-5fb9bd59b057.png)

**Comment by gperrin12** [comment]
Hey-

My instance is ami-25615740 (Amazon Linux AMI 2017.09.1 (HVM), SSD Volume Type)

I've repulled the repo, but getting a new error (see below)
<img width="595" alt="screen shot 2018-04-15 at 1 53 14 pm" src="https://user-images.githubusercontent.com/9039296/38781509-71b0a1a8-40b4-11e8-8c0c-5a2187ce9148.png">

**Comment by vr00n** [comment]
I have updated the Dockerfile - can you repull and try again?

**Comment by gperrin12** [comment]
Cool - seems to have run, but might've run out of room (on the free tier) and then got a permissions error

<img width="938" alt="screen shot 2018-04-15 at 5 16 20 pm" src="https://user-images.githubusercontent.com/9039296/38783489-ce495b32-40d0-11e8-88c0-b9bc40d399f2.png">

**Comment by vr00n** [comment]
You can do a `df -H` to see your disk spalce.

Here is my mac's

![image](https://user-images.githubusercontent.com/4397663/38784130-b0281e00-40ca-11e8-81bf-baf4ebb4782c.png)

**Comment by aaron-15** [comment]
Is this issue resolved?

**Comment by vr00n** [comment]
yes - thanks @aaron-15 👍
